// Generated by SvelteKit - DO NOT EDIT
/// <reference types="@sveltejs/kit" />

declare module '$env/dynamic/private' {
	export const env: Record<string, string | undefined>;
	export const DATABASE_URL: string;
}
